### ISSUE TITLE
Failed to Build Image

### ISSUE THREAD

**Issue by thewarden** [TheSin-/debian-mini-rpi#1]
I changed the packages.txt to contain the following other wise I left everything else as is.

isc-dhcp-client rsyslog cron openssh-client nano omxplayer

Please refer to the attached file for the output of building the image.

[output.txt](https://github.com/TheSin-/debian-mini-rpi/files/38232/output.txt)

**Comment by TheSin-** [comment]
very odd, it's failing in the createimg script, I haven't had this issue.  looks like everything built fine it just failed to make the img.  I'm looking into it see if I can recreate this issue, to track it down.

Can you tell me about the host computer.  Is it debian or ubuntu etc etc?

**Comment by thewarden** [comment]
Oh yes sorry. I ran it on Debian Jessie amd64. I'm not able to access the system right now but tomorrow I'll get the information regarding the sfdisk. If there is anything more that you need let me know.

**Comment by TheSin-** [comment]
hmm debian jessie should be fine, I'll build a fresh VM tonight or tomorrow and see if I can replicate the issue, did you run it as a user with sudo, I always run it as root I assumed sudo would be fine but perhaps that is the issue, I'll test that as well and fix it if need be.  It should be able to run as sudo.

**Comment by thewarden** [comment]
Yes I used sudo. Not suppose to use root. Nah that can't be the issue. I use sudo all the time. I of course could do sudo su and try tomorrow.

**Comment by TheSin-** [comment]
it's okay I"m trying with sudo from a reg user right now, I'd be extremely surprised that is the issue but I want to figure this out it's making me crazy :)

**Comment by TheSin-** [comment]
okay I'm 100% sure that a reg user + sudo works so that isn't it.  Guess I'll wait till tomorrow to get the sfdisk version from you, also please do which sfdisk just to be thorough

**Comment by thewarden** [comment]
Here is the information you were asking for. It appears you must be running Debian Stretch/Sid in order to have sfdisk (util-linux) v2.27.1. I hope this helps.

    $ uname -a
    Linux keiko 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

    $ sudo sfdisk -v
    sfdisk from util-linux 2.25.2

    $ sudo which sfdisk
    /sbin/sfdisk

**Comment by TheSin-** [comment]
yes I am on Stretch, as said above I'll have to make a jessie box since I have none.  I'm away for most of today but when I get back I"ll work on a jessie box so I can see if I can fix that very small portion of script, I had no idea sfdisk was so different in jessie.  But I'll get it fixed.

**Comment by thewarden** [comment]
I wouldn't think there would be that big of a difference either. Good thing I tested it out :-).

**Comment by TheSin-** [comment]
okay I have switched the script to use fdisk, I'm testing it now.  hopefully it'll work out and fix this.  If the test works out I'll commit it so you can give it a shot tomorrow, I didn't have a change to get a jessie system installed today, but I may work on that tomorrow if this doesn't work.

**Comment by TheSin-** [comment]
just wondering if you had a chance to try it again since I switched to disk?  I still haven't had a chance to setup a jessie VM, hopefully this week if I don't hear back from you.

**Comment by thewarden** [comment]
I cloned everything again and ran the build process. However the build still failed. Please see the attached output.

[output.txt](https://github.com/TheSin-/debian-mini-rpi/files/41717/output.txt)

**Comment by TheSin-** [comment]
think we have it now, we a rogue i in the script since I use vi ;)

**Comment by thewarden** [comment]
Awesome, this issue has now been resolved. I have successfully built an image.

**Comment by TheSin-** [comment]
Confirmed solved, thank you so much for your patience and feedback it's much appreciated.
