### ISSUE TITLE
Missing Userland bcm_host.h

### ISSUE THREAD

**Issue by thewarden** [TheSin-/debian-mini-rpi#2]
I believe the bcm_host.h is missing within the userland. I tried to compile pngview from raspimx (https://github.com/AndrewFromMelbourne/raspidmx). The compilation failed to locate bcm_host.h. 

However pngview compiled successfully on Raspbian.

**Run the following on debian-mini-rpi:**
    $ find /opt/vc -name bcm_host.h

**Run the following on Raspbian:**
    $ find /opt/vc -name bcm_host.h
    /opt/vc/include/bcm_host.h

**Comment by TheSin-** [comment]
apt-get install libraspberrypi-dev
